```{r}
install.packages(c("tm", "tidytext"))
library(tm)
library(tidytext)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stringr)
```
```{r}
#load data
customer_data <- read.csv("QVI_purchase_behaviour.csv")
transaction_data <- read.csv("QVI_transaction_data1.csv")
#data structure
str(customer_data)
str(transaction_data)
#display data
head(customer_data)
head(transaction_data)
```
```{r}
#convert integers in DATE column to actual date
transaction_data$DATE <- as.Date(transaction_data$DATE, origin = "1899-12-30")
```
```{r}
#Text analysis on product names

# Create a Corpus
corpus <- Corpus(VectorSource(transaction_data$PROD_NAME))

# Preprocess the Text
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords("en"))  
# Remove punctuation, numbers and common English stopwords

# Create a Document-Term Matrix (DTM)
dtm <- DocumentTermMatrix(corpus)

# Convert DTM to a Data Frame
dtm_df <- as.data.frame(as.matrix(dtm))

# Summarize Word Frequencies
word_frequencies <- colSums(dtm_df)
sorted_word_frequencies <- sort(word_frequencies, decreasing = TRUE)

# Display 20 Most Common Words
head(sorted_word_frequencies, 20) 

```

```{r}
#The 13th most frequent word is salsa with an occurrence of 18094 times. We will remove salsa products from the dataset since we are only interested in the chips category.

# Remove rows containing 'salsa' in the ProductName column
transaction_data<- transaction_data[!grepl("salsa", transaction_data$PROD_NAME, ignore.case = TRUE), ]
head(transaction_data)
```
```{r}
#There are no nulls in the dataset.
sum(is.na(transaction_data))
#summarize the cleaned dataset.
summary(customer_data)
summary(transaction_data)
#The max of total sale is 650$ which is significantly larger than the average sales level.

# Find rows where TotalSales equals 650
outlier<-transaction_data[transaction_data$TOT_SALES == 650, ]
print(outlier)
#As can be seen from the outlier data frame, the same customer has made the annual purchase of 200 bags of the same chips product twice resulting in 650$ sales.
outlier_customer<-customer_data[customer_data$LYLTY_CARD_NBR== 226000, ]
print(outlier_customer)
# As can be seen from the customer outlier data frame, this customer is at the life stage of older families and has premium status.
#Hence, the customer might be buying chips for other purposes instead. 

#remove outlier
transaction_data <- transaction_data[transaction_data$LYLTY_CARD_NBR != 226000, ]
customer_data<-customer_data[customer_data$LYLTY_CARD_NBR!=226000,]
```
```{r}
#re-examine data after removing outliers
summary(customer_data)
summary(transaction_data)
```

```{r}
Sys.setlocale(locale = "English")
# Convert the Date column to a Date object
transaction_data$DATE <- as.Date(transaction_data$DATE)

# Count the number of transactions by date
transactions_by_date <- table(transaction_data$DATE)

# Plot transactions over time using a line chart
plot(as.Date(names(transactions_by_date)), transactions_by_date,
     type = "l",
     col = "blue",
     lwd = 2, 
     xlab = "Date",
     ylab = "Number of Transactions",
     main = "Transactions Over Time")
grid()

#The transactions zoom in December possibly due to the Christmas and winter break.
```

```{r}
# Extract package size from the ProductName column
transaction_data <- transaction_data %>%
  mutate(Package_size = as.numeric(str_extract(PROD_NAME, "\\d+")))

# Display the modified data frame
head(transaction_data)
```

```{r}
# Plot histogram for the number of transactions by pack size
ggplot(transaction_data, aes(x = Package_size)) +
  geom_bar(width = 3.5) +
  labs(title = "Number of Transactions by Pack Size",
       x = "Pack Size",
       y = "Number of Transactions") +
  theme_minimal()

# Plot histogram for the quantity purchased by pack size
ggplot(transaction_data, aes(x = Package_size, y = PROD_QTY)) +
  geom_bar(stat = "identity",width = 3.5, fill = "skyblue") +
  labs(title = "Quantity Purchased by Pack Size",
       x = "Pack Size",
       y = "Quantity Purchased") +
  theme_minimal()
```
```{r}
# Extract the first word from the ProductName column and store it in a new column 'Brand'
transaction_data <- transaction_data %>%
  mutate(Brand = str_extract(PROD_NAME, "\\w+"))
head(transaction_data)

# Create a table to count transactions per brand
transactions_by_brand <- table(transaction_data$Brand)

# Convert the result to a data frame (optional)
transactions_by_brand_df <- as.data.frame(transactions_by_brand)

# Display the result
print(transactions_by_brand_df)
```

```{r }
#### Merge transaction data to customer data
data <- merge(transaction_data, customer_data, all.x = TRUE)
head(data)
sum(is.na(data))
#There are no nulls in the merged dataset.
```
